Repository code-star/codestar-website-react, pull requests merged in 2018-11, with the labels that each got.

#34 Architecture
  docs/CONTRIBUTING.md
Labels: documentation

#41 Feature/trainings
  package.json
  public/locales/en/events.json
  public/locales/nl/events.json
  src/App.jsx
  src/App.test.js
  src/EventCard/EventCard.tsx
  src/EventsHeader/EventsHeaderButton.jsx
  src/EventsHeader/EventsHeaderButton.module.css
  src/EventsHeader/EventsHeaderMessage.tsx
  src/EventsHeader/__snapshots__/DetailsSection.test.tsx.snap
  src/__snapshots__/App.test.js.snap
  src/__tests__/eventsService/getCachedRecentTweets.test.js
  src/components/Molecules/List/Events/Events.test.jsx
  src/components/Molecules/List/Events/Events.tsx
  src/components/Molecules/List/Events/NextEventsBlock.tsx
  src/components/Molecules/List/TweetList/TweetList.module.scss
  src/components/Molecules/List/TweetList/TweetList.stories.js
  src/components/Molecules/List/TweetList/TweetList.test.tsx
  src/components/Molecules/List/TweetList/TweetList.tsx
  src/components/Molecules/List/TweetList/__snapshots__/TweetList.test.js.snap
  src/components/Molecules/List/TweetList/__snapshots__/TweetList.test.tsx.snap
  src/components/Molecules/TrainingsSection/TrainingsSection.module.scss
  src/components/Molecules/TrainingsSection/TrainingsSection.stories.js
  src/components/Molecules/TrainingsSection/TrainingsSection.test.tsx
  src/components/Molecules/TrainingsSection/TrainingsSection.tsx
  src/components/Molecules/TrainingsSection/__snapshots__/TrainingsSection.test.tsx.snap
  src/components/Organisms/EventsHeader/DetailsSection.test.tsx
  src/components/Organisms/EventsHeader/DetailsSection.tsx
  src/components/Organisms/EventsHeader/EventsHeader.module.scss
  src/components/Organisms/EventsHeader/EventsHeader.tsx
  src/components/Organisms/EventsHeader/EventsHeaderButton.module.scss
  src/components/Organisms/EventsHeader/EventsHeaderButton.tsx
  src/components/Organisms/EventsHeader/EventsHeaderMessage.tsx
  src/components/Organisms/EventsHeader/HeaderContent.test.tsx
  src/components/Organisms/EventsHeader/HeaderContent.tsx
  src/components/Organisms/EventsHeader/__snapshots__/DetailsSection.test.tsx.snap
  src/components/Organisms/EventsHeader/__snapshots__/HeaderContent.test.tsx.snap
  src/components/Organisms/EventsHeader/constants.jsx
  src/containers/EventsContainer/EventsContainer.helpers.ts
  src/containers/EventsContainer/EventsContainer.interfaces.ts
  src/containers/EventsContainer/EventsContainer.test.jsx
  src/containers/EventsContainer/EventsContainer.tsx
  src/containers/NavContainer/NavContainer.jsx
  src/eventsService.ts
  src/theming/config.module.scss
Labels: ready to merge

#42 Updating architecture
  docs/CONTRIBUTING.md
Labels: documentation

#48 Typescript via react-scripts
  .gitignore
  package-lock.json
  package.json
  scripts/ensureYarn.js
  src/Animations/AnimatedLogo.jsx
  src/CaseHeader/CaseHeader.tsx
  src/Cases/Cases.tsx
  src/EventCard/EventCard.tsx
  src/Jobs/Jobs.tsx
  src/OurStack/__snapshots__/OurStack.test.jsx.snap
  src/__snapshots__/App.test.js.snap
  src/components/Molecules/EventsButton/__snapshots__/EventsButton.test.tsx.snap
  src/components/Molecules/List/Events/Events.tsx
  src/components/Molecules/List/TweetList/__snapshots__/TweetList.test.tsx.snap
  src/components/Molecules/TeamCarousel/TeamCarousel.tsx
  src/components/Molecules/TrainingsSection/TrainingsSection.tsx
  src/components/Molecules/TrainingsSection/__snapshots__/TrainingsSection.test.tsx.snap
  src/components/Organisms/EventsHeader/DetailsSection.tsx
  src/components/Organisms/EventsHeader/EventsHeaderButton.tsx
  src/components/Organisms/EventsHeader/EventsHeaderMessage.tsx
  src/components/Organisms/EventsHeader/HeaderContent.tsx
  src/components/Organisms/EventsHeader/__snapshots__/DetailsSection.test.tsx.snap
  src/components/Organisms/EventsHeader/__snapshots__/HeaderContent.test.tsx.snap
  src/components/Pages/About/About.tsx
  src/react-app-env.d.ts
  src/setupTests.ts
  tsconfig.json
  tsconfig.prod.json
  tsconfig.test.json
  yarn.lock
Labels: do not merge
