Repository code-star/codestar-website-react, pull requests merged in 2018-10, with the labels that each got.

#29 #1 ~ atomic design in contributing guidelines
  README.md
  docs/CONTRIBUTING.md
  src/components/Organisms/.gitkeep
  src/components/Pages/.gitkeep
  src/components/Templates/.gitkeep
Labels: documentation, ready to merge

#30 #2 ~ app test
  README.md
  package.json
  src/App.test.js
  src/EventsHeader/__snapshots__/DetailsSection.test.tsx.snap
  src/EventsHeader/__snapshots__/HeaderContent.test.tsx.snap
  src/OurStack/__snapshots__/OurStack.test.jsx.snap
  src/__snapshots__/App.test.js.snap
  src/components/Molecules/Card/Tweet/Tweet.stories.js
  src/components/Molecules/List/TweetList/TweetList.stories.js
Labels: enhancement, ready to merge

#31 #3 ~ events page recent tweets
  .gitignore
  .storybook/addons.js
  .storybook/config.js
  README.md
  docs/getRecentTweets.md
  package-lock.json
  package.json
  public/locales/en/events.json
  public/locales/nl/events.json
  public/mock/get-recent-tweets.json
  src/App.jsx
  src/ScrollToTop.jsx
  src/codestarMuiTheme.js
  src/components/Atoms/.gitkeep
  src/components/Atoms/Action/Button/Button.module.css
  src/components/Atoms/Action/Button/Button.module.scss
  src/components/Atoms/Action/Button/Button.stories.js
  src/components/Atoms/Action/Button/Button.test.js
  src/components/Atoms/Action/Button/Button.tsx
  src/components/Atoms/Action/Button/__snapshots__/Button.test.js.snap
  src/components/Atoms/Action/Button/index.ts
  src/components/Atoms/Text/Heading/Heading.module.css
  src/components/Atoms/Text/Heading/Heading.module.scss
  src/components/Atoms/Text/Heading/Heading.stories.js
  src/components/Atoms/Text/Heading/Heading.test.js
  src/components/Atoms/Text/Heading/Heading.tsx
  src/components/Atoms/Text/Heading/__snapshots__/Heading.test.js.snap
  src/components/Atoms/Text/Heading/index.ts
  src/components/Atoms/Text/Label/Label.module.css
  src/components/Atoms/Text/Label/Label.module.scss
  src/components/Atoms/Text/Label/Label.stories.js
  src/components/Atoms/Text/Label/Label.test.js
  src/components/Atoms/Text/Label/Label.tsx
  src/components/Atoms/Text/Label/__snapshots__/Label.test.js.snap
  src/components/Atoms/Text/Label/index.ts
  src/components/Molecules/Card/Tweet/Tweet.module.css
  src/components/Molecules/Card/Tweet/Tweet.module.scss
  src/components/Molecules/Card/Tweet/Tweet.stories.js
  src/components/Molecules/Card/Tweet/Tweet.test.js
  src/components/Molecules/Card/Tweet/Tweet.tsx
  src/components/Molecules/Card/Tweet/__snapshots__/Tweet.test.js.snap
  src/components/Molecules/Card/Tweet/index.ts
  src/components/Molecules/List/Events/Events.tsx
  src/components/Molecules/List/Events/NextEventsBlock.tsx
  src/components/Molecules/List/TweetList/TweetList.test.js
  src/components/Molecules/List/TweetList/TweetList.tsx
  src/components/Molecules/List/TweetList/__snapshots__/TweetList.test.js.snap
  src/i18n.js
  src/modules/EventsContainer/EventsContainer.tsx
  src/modules/NavContainer/NavContainer.jsx
Labels: feature, ready to merge

#37 Add BrowserUpdate message
  public/index.html
Labels: ready to merge

#38 Feature/scss modules
  .gitignore
  .storybook/webpack.config.js
  @types/custom.d.ts
  package-lock.json
  package.json
  src/About/About.module.css
  src/About/About.tsx
  src/App.jsx
  src/NavBar/__snapshots__/EventsButton.test.tsx.snap
  src/components/Molecules/List/Events/Events.module.css
  src/components/Molecules/List/Events/Events.module.scss
  src/components/Molecules/List/TweetList/TweetList.stories.js
  src/components/Molecules/TeamCarousel/Team.json
  src/components/Molecules/TeamCarousel/TeamCarousel.module.scss
  src/components/Molecules/TeamCarousel/TeamCarousel.stories.js
  src/components/Molecules/TeamCarousel/TeamCarousel.tsx
  src/components/Molecules/TeamCarousel/renderControls.tsx
  src/components/Pages/About/About.module.scss
  src/components/Pages/About/About.tsx
  src/theming/config.module.css
Labels: help wanted

#40 Feature/refactor eventsbutton
  package-lock.json
  package.json
  src/components/Molecules/EventsButton/EventsButton.stories.js
  src/components/Molecules/EventsButton/EventsButton.test.tsx
  src/components/Molecules/EventsButton/EventsButton.tsx
  src/components/Molecules/EventsButton/__snapshots__/EventsButton.test.tsx.snap
  src/components/Molecules/NavBar/NavBar.stories.js
  src/components/Molecules/NavBar/NavBar.tsx
  src/components/Molecules/TeamCarousel/TeamCarousel.stories.js
  src/modules/NavContainer/NavContainer.jsx
Labels: enhancement, ready to merge
